name =input("Enter a name: ") 
adj1 =input("Enter an adjective: ")
adj2 =input("Enter an adjective: ")
adverb =input("Enter an adverb: ")
food =input("Enter a food: ") 
food2 =input("Enter another food: ")
noun =input("Enter a noun: ")
place =input("Enter a place: ")
verb =input("Enter a verb: ")
print("\n"+name+" was planning a dream vacation to "+place+ "\n"+name+" was especially looking forward to trying the local \ncuisine, including "+adj1+" "+food+" "+food2+"\n\n"+name+ " will have to practice the language "+adverb+ " to \n make it easier to "+verb+" with people.\n\n"+name+" has a long list of sights to see, including the \n"+noun+" museum and the "+adj2+" park.")